// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')



<script type="text/javascript">
//设置cookie
function setCookie(name,value,time){
   var strsec = getsec(time);
   var exp = new Date();
   exp.setTime(exp.getTime() + strsec*1);
   document.cookie = name + "="+ escape (value) + ";expires=" + exp.toGMTString();
}
function getsec(str){
  var str1=str.substring(1,str.length)*1;
  var str2=str.substring(0,1);
  if (str2=="s")
  {
    return str1*1000;
  }
  else if (str2=="h")
  {
    return str1*60*60*1000;
  }
  else if (str2=="d")
  {
    return str1*24*60*60*1000;
  }
}
//获取cookie
function getCookie(name){
  var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");
  if(arr=document.cookie.match(reg))
   return unescape(arr[2]);
  else
   return null;
}

//是否实名、是否绑卡
var realNametf = false;
var bankCodetf = false;
/*判断是否注册联动用户 */
$(function(){
	isrealName ();
	isDirlogShow ();
	lighten ();
	console.log(window.location.pathname);
});

function isrealName (){
   	$.ajax({
      	url: $('#path').val() + "/cgUser/getRegisterInfo", // 是否实名、绑卡
      	type: "post",
      	dataType: "json",
      	data: { },
      	async : false,
      	success: function (data) {
			if(data.realName == ''){
				realNametf = false;
			}else{
				realNametf = true;
			};
			if(data.bankCode == ''){
				bankCodetf = false;
			}else{
				bankCodetf = true;
			}
      	},
     	error: function (data){
     		realNametf = false;
     		bankCodetf = false;
     	}
  	});
}
//是否显示弹出框
function isDirlogShow (){
	if(realNametf==false){//未注册
		$('html,body').animate({scrollTop: '0px'}, 800);
		$("#goReal").show();   
		$("body").css("overflow","hidden");
	} else if(realNametf==true && bankCodetf==false){//已经注册用户但未绑卡
	   $('html,body').animate({scrollTop: '0px'}, 800);   
	   $("#goReal").show();
		$("body").css("overflow","hidden"); 
   } else{
	   $("#Prompt").hide();
	   $("#bindCard_list").hide(); 
   }
}
function lighten (){
	//左侧列表是否点亮
   	if(realNametf==false){//未注册
		$(".nameLi1").css('display','block');
	} else{
		$(".nameLi2").css('display','block');
	}
   	if(bankCodetf==false){//未注册
		$(".cardLi1").css('display','block');
	} else{
		$(".cardLi2").css('display','block');
	}
}
/*关闭联动开户遮罩层  */
function shutPrompt(){
	$("#goReal").hide();
	$('html,body').animate({scrollTop: '0px'}, 800); 
	$("body").css("overflow","auto");
}
//去认证按钮
 function goRealname (){
	   $.ajax({
       	url: $('#path').val() + "/cgUser/register", // 去认证
       	type: "post",
       	dataType: "json",
       	data: {
       		bizType : '01',
      		returnUrl : 'http://'+document.domain + window.location.pathname
       	},
       	success: function (data) {
       		console.log(data);
       		// result为1时，表示成功
       		if (data.result == 1) {
       			var myWindow = window.open('', '_blank');
       			myWindow.document.write(data.resultObject);
       		} else {
       			alert(data.errInfo);
       		}
       	},
       	error: function (data){
       		console.log(data);
       	}
   	});	
 }
